name: Check VPS Expiry

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  check-expiry:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Create config file
      run: |
        echo '{
          "dingtalk": {
            "enabled": true,
            "webhook": "${{ secrets.DINGTALK_WEBHOOK }}",
            "secret": "${{ secrets.DINGTALK_SECRET }}"
          },
          "telegram": {
            "enabled": true,
            "bot_token": "${{ secrets.TELEGRAM_BOT_TOKEN }}",
            "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}"
          }
        }' > config.json
    
    - name: Run expiry check
      run: python vps_monitor.py 