name: Update VPS Info

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次（0点和12点）
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 添加写入权限
    
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run monitor script and update data
      run: |
        pwd  # 显示当前目录
        ls -la  # 显示文件列表
        python update_vps_data.py
        echo "更新后的文件内容:"
        tail -n 20 index.html  # 显示文件最后20行
      env:
        DINGTALK_TOKEN: ${{ secrets.DINGTALK_TOKEN }}
        DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
    
    - name: Commit changes
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git status  # 显示git状态
        git commit -m "Auto update VPS data" || echo "No changes to commit"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}